structure(list(url = "https://api-ccte.epa.gov/bioactivity/search/by-dtxsid/DTXSID7020182", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Fri, 22 Mar 2024 15:10:19 GMT", `cache-control` = "no-cache, must-revalidate", 
        `x-vcap-request-id` = "08a328e0-7b0c-4bd0-5877-e06d4e27d44b", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 c22d4946ef5faea12b8d3942ceb9259a.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "IsZzsG7qfk4ToTyXG32T-iAbsTPURzEuSVYUBpLzrckSVp55cQcW-A=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Fri, 22 Mar 2024 15:10:19 GMT", `cache-control` = "no-cache, must-revalidate", 
            `x-vcap-request-id` = "08a328e0-7b0c-4bd0-5877-e06d4e27d44b", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 c22d4946ef5faea12b8d3942ceb9259a.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "IsZzsG7qfk4ToTyXG32T-iAbsTPURzEuSVYUBpLzrckSVp55cQcW-A=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-03-22T15:10:19.264+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/bioactivity/search/by-dtxsid/DTXSID7020182\"\n}"), 
    date = structure(1711120219, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.8e-05, 
    connect = 0, pretransfer = 0.000136, starttransfer = 0.253742, 
    total = 0.253773)), class = "response")
